name: ssh
on: push
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: SSH connection to Actions
        uses: vpsbash/debugger-action@master
