name: Hello World
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: 1
        run: |
          curl myip.ipip.net
          mkdir 1
          sudo curl -fsL https://ilemonra.in/LemonBenchIntl | sudo bash -s full 

    
