name: Hello World
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: 1
        run: |
          sudo apt update
          sudo apt install curl
          mkdir 1
          sudo curl -fsL https://ilemonra.in/LemonBenchIntl | bash -s full >> 1/1.sh
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: 1
          path: 1
        
    
